package org.java.str;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * @author SibyThomas
 *
 */
public class FindTheDifference {
	/**
	 * Input: s = "abcd" t = "abcde"
	 * 
	 * Output: e
	 * 
	 * Explanation: 'e' is the letter that was added.
	 * 
	 * @param s
	 * @param t
	 * @return
	 */
	public char findTheDifference(String s, String t) {
		int[] cnt = new int[128];
		for (char ch : t.toCharArray())
			cnt[ch]++;
		for (char ch : s.toCharArray())
			cnt[ch]--;
		for (char ch = 0; ch < 128; ch++)
			if (cnt[ch] > 0)
				return ch;
		return 0;
	}

}